COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= fifo_full_press_temp_with_sensortime.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bmp3.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk